# Generated by Django 4.2 on 2023-04-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_parameterset_reconnection_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetplayer',
            name='hex_color',
            field=models.CharField(default='0x000000', max_length=8, verbose_name='Hex Color'),
        ),
        migrations.AddField(
            model_name='parametersetplayer',
            name='start_x',
            field=models.IntegerField(default=50, verbose_name='Start Location X'),
        ),
        migrations.AddField(
            model_name='parametersetplayer',
            name='start_y',
            field=models.IntegerField(default=50, verbose_name='Start Location Y'),
        ),
    ]
