# Generated by Django 4.2 on 2023-04-10 16:54

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_parametersetplayer_hex_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='world_state',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Current Session State'),
        ),
    ]
