# Generated by Django 4.2 on 2023-04-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_session_world_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='tokens_per_period',
            field=models.IntegerField(default=100, verbose_name='Number of tokens each period'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='world_height',
            field=models.IntegerField(default=10000, verbose_name='Height of world in pixels'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='world_width',
            field=models.IntegerField(default=10000, verbose_name='Width of world in pixels'),
        ),
    ]
