# Generated by Django 4.2 on 2023-05-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_parameterset_tokens_per_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='cool_down_length',
            field=models.IntegerField(default=10, verbose_name='Cool Down Length'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='interaction_length',
            field=models.IntegerField(default=10, verbose_name='Interaction Length'),
        ),
    ]
