# Generated by Django 4.2 on 2023-05-25 23:24

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_parameterset_cool_down_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPeriodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_remaining', models.IntegerField(default=0, verbose_name='Time Remaining')),
                ('type', models.CharField(default='', max_length=255, verbose_name='Event Type')),
                ('data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='Event Data')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_period_events', to='main.sessionperiod')),
            ],
            options={
                'verbose_name': 'Session Period Event',
                'verbose_name_plural': 'Session Period Events',
                'ordering': ['time_remaining'],
            },
        ),
    ]
