# Generated by Django 4.2.1 on 2023-05-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_sessionevent_session_period_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionPlayerChat',
        ),
    ]
