# Generated by Django 4.2 on 2023-05-31 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_remove_session_finished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='current_period',
        ),
    ]
