# Generated by Django 4.2 on 2023-05-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_session_current_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='time_remaining',
        ),
    ]
