# Generated by Django 4.2 on 2023-06-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_session_time_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='controlling_channel',
            field=models.CharField(default='', max_length=300),
        ),
    ]
