# Generated by Django 4.2.1 on 2023-06-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_session_controlling_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='interaction_range',
            field=models.IntegerField(default=300, verbose_name='Interaction Range'),
        ),
    ]
