# Generated by Django 4.2.1 on 2023-06-07 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_parameterset_interaction_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevent',
            name='session_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_events_b', to='main.sessionplayer'),
        ),
    ]
