# Generated by Django 4.2.1 on 2023-07-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_sessionevent_session_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'ordering': ['period_number', '-time_remaining'], 'verbose_name': 'Session Event', 'verbose_name_plural': 'Session Events'},
        ),
        migrations.RemoveField(
            model_name='session',
            name='timer_running',
        ),
    ]
