# Generated by Django 4.2.6 on 2023-10-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_sessionevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='avatar_animation_speed',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='Animation Speed'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='avatar_bound_box_percent',
            field=models.DecimalField(decimal_places=2, default=0.75, max_digits=3, verbose_name='Avatar Bound Box Percent'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='avatar_move_speed',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Move Speed'),
        ),
        migrations.AddField(
            model_name='parameterset',
            name='avatar_scale',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Avatar Scale'),
        ),
    ]
