# Generated by Django 4.2.6 on 2023-10-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_parameterset_break_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionperiod',
            name='consumption_completed',
            field=models.BooleanField(default=False),
        ),
    ]
