# Generated by Django 4.2.6 on 2023-10-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_sessionperiod_consumption_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionperiod',
            name='consumption_completed',
        ),
    ]
