# Generated by Django 4.2.7 on 2023-11-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_parametersetnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, default='Info Here', max_length=100, null=True, verbose_name='Info')),
                ('start_x', models.IntegerField(default=50, verbose_name='Location X')),
                ('start_y', models.IntegerField(default=50, verbose_name='Location Y')),
                ('width', models.IntegerField(default=50, verbose_name='Width')),
                ('height', models.IntegerField(default=50, verbose_name='Height')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_walls', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Wall',
                'verbose_name_plural': 'Parameter Set Walls',
                'ordering': ['id'],
            },
        ),
    ]
