# Generated by Django 4.2.6 on 2023-11-01 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_parametersetwall'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Name Here', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_groups', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Group',
                'verbose_name_plural': 'Parameter Set Groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='parametersetplayer',
            name='parameter_set_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_set_players_b', to='main.parametersetgroup'),
        ),
    ]
