# Generated by Django 4.2.6 on 2023-11-02 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_parametersetbarrier'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterSetGround',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, default='Info Here', max_length=100, null=True, verbose_name='Info')),
                ('x', models.IntegerField(default=50, verbose_name='Location X')),
                ('y', models.IntegerField(default=50, verbose_name='Location Y')),
                ('width', models.IntegerField(default=50, verbose_name='Width')),
                ('height', models.IntegerField(default=50, verbose_name='Height')),
                ('tint', models.CharField(default='0x000000', max_length=8, verbose_name='Tint (Hex Color)')),
                ('texture', models.CharField(default='Name Here', verbose_name='Texture Name')),
                ('rotation', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('scale', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parameter_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_set_grounds', to='main.parameterset')),
            ],
            options={
                'verbose_name': 'Parameter Set Ground Element',
                'verbose_name_plural': 'Parameter Set Ground Elements',
                'ordering': ['id'],
            },
        ),
    ]
