# Generated by Django 4.2.7 on 2023-11-20 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_parametersetground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='instruction_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parameter_sets', to='main.instructionset'),
        ),
        migrations.AlterField(
            model_name='parametersetground',
            name='tint',
            field=models.CharField(default='0xFFFFFF', max_length=8, verbose_name='Tint (Hex Color)'),
        ),
    ]
