# Generated by Django 4.2.7 on 2023-11-21 17:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_parameterset_instruction_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpDocsSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Title')),
                ('text', tinymce.models.HTMLField(default='', max_length=100000, verbose_name='Help Doc Text')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('instruction_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_docs_subject', to='main.instructionset')),
            ],
            options={
                'verbose_name': 'Help Doc Subject',
                'verbose_name_plural': 'Help Docs Subject',
                'ordering': ['title'],
            },
        ),
        migrations.AddConstraint(
            model_name='helpdocssubject',
            constraint=models.UniqueConstraint(fields=('instruction_set', 'title'), name='unique_help_doc_subject'),
        ),
    ]
