# Generated by Django 4.2.8 on 2023-12-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_helpdocssubject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetbarrier',
            name='parameter_set_players',
            field=models.ManyToManyField(related_name='parameter_set_barriers_c', to='main.parametersetplayer'),
        ),
    ]
