# Generated by Django 4.2.10 on 2024-03-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_sessionperiod_summary_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionset',
            name='action_page_1',
            field=models.IntegerField(default=1, verbose_name='Required Action: 1'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_2',
            field=models.IntegerField(default=2, verbose_name='Required Action: 2'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_3',
            field=models.IntegerField(default=3, verbose_name='Required Action: 3'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_4',
            field=models.IntegerField(default=4, verbose_name='Required Action: 4'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_5',
            field=models.IntegerField(default=5, verbose_name='Required Action: 5'),
        ),
        migrations.AddField(
            model_name='instructionset',
            name='action_page_6',
            field=models.IntegerField(default=6, verbose_name='Required Action: 6'),
        ),
    ]
