# Generated by Django 4.2.10 on 2024-03-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_instructionset_action_page_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='id_string',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
