# Generated by Django 4.2.11 on 2024-05-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_remove_parameterset_private_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetplayer',
            name='hex_color',
            field=models.CharField(default='0x000000', max_length=30, verbose_name='Hex Color'),
        ),
    ]
