# Generated by Django 4.2.11 on 2024-05-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_profileloginattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileloginattempt',
            old_name='my_profile',
            new_name='user',
        ),
    ]
