# Generated by Django 4.2.15 on 2024-08-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_alter_profileloginattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='token_cents_value',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='Token Cents Value'),
        ),
    ]
