# Generated by Django 4.2.15 on 2024-09-03 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_parameterset_token_cents_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='parameter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_c', to='main.parameterset'),
        ),
    ]
