# Generated by Django 4.2.17 on 2024-12-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_session_parameter_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameterset',
            name='reconnection_limit',
            field=models.IntegerField(default=25, verbose_name='Limit Subject Screen Reconnection Trys'),
        ),
    ]
