# Generated by Django 4.2.17 on 2024-12-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_parameterset_reconnection_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='website_instance_id',
            field=models.CharField(default='', max_length=300, verbose_name='Website Instance ID'),
        ),
    ]
