# Generated by Django 4.2.17 on 2024-12-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_session_website_instance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='website_instance_id',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Website Instance ID'),
        ),
    ]
