# Generated by Django 4.2.16 on 2024-12-18 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0062_alter_session_website_instance_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('can_edit_instructions', models.BooleanField(default=False, verbose_name='Can Edit Instructions')),
                ('mfa_hash', models.CharField(blank=True, max_length=50, null=True, verbose_name='Multi-factor Hash')),
                ('mfa_required', models.BooleanField(default=False, verbose_name='Multi-factor Required')),
                ('mfa_setup_complete', models.BooleanField(default=False, verbose_name='Multi-factor Setup Complete')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
