# Generated by Django 4.2.16 on 2024-12-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_auto_20241218_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileloginattempt',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_login_attempts', to='main.profile'),
        ),
    ]
