# Generated by Django 4.2.16 on 2024-12-18 18:25

from django.db import migrations

from main.models import ProfileLoginAttempt

def user_to_profile(apps, schema_editor):
    '''
    move user to profile
    '''
    
    for profile_login_attempt in ProfileLoginAttempt.objects.all():
        profile_login_attempt.profile = profile_login_attempt.user.profile
        profile_login_attempt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_profileloginattempt_profile'),
    ]

    operations = [
        migrations.RunPython(user_to_profile),
    ]
