# Generated by Django 4.2.16 on 2024-12-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20241218_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileloginattempt',
            name='user',
        ),
    ]
