# Generated by Django 4.2.16 on 2025-01-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_remove_profileloginattempt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='parameter_set',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.parameterset'),
        ),
    ]
