# Generated by Django 4.2.16 on 2025-01-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_alter_session_parameter_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='default_parameter_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.parameterset'),
        ),
    ]
