# Generated by Django 5.2.2 on 2025-08-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_parameters_default_parameter_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='chat_gpt_mode',
            field=models.CharField(choices=[('Off', 'Off'), ('With Context', 'With Context'), ('Without Context', 'Without Context')], default='Off', max_length=20, verbose_name='ChatGPT Mode'),
        ),
    ]
