# Generated by Django 5.2.2 on 2025-08-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_parameterset_chat_gpt_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionplayer',
            name='chat_gpt_prompt',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Chat GPT Prompt'),
        ),
    ]
