# Generated by Django 5.2.2 on 2026-04-20

from django.db import migrations, models


def clear_parameter_set_json_cache(apps, schema_editor):
    ParameterSet = apps.get_model('main', 'ParameterSet')
    ParameterSet.objects.all().update(json_for_session=None)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_parametersetground_render_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametersetground',
            name='enable_clipping',
            field=models.BooleanField(default=True, verbose_name='Enable Clipping'),
        ),
        migrations.AlterModelOptions(
            name='parametersetground',
            options={
                'ordering': ['id'],
                'verbose_name': 'Parameter Set Ground Element',
                'verbose_name_plural': 'Parameter Set Ground Elements',
            },
        ),
        migrations.RunPython(clear_parameter_set_json_cache, noop_reverse),
    ]
