# Generated by Django 5.2.13 on 2026-04-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_parametersetground_enable_clipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametersetground',
            name='enable_clipping',
            field=models.BooleanField(default=False, verbose_name='Enable Clipping'),
        ),
    ]
