# Generated by Django 5.2.13 on 2026-04-20

from django.db import migrations, models


def clear_parameter_set_json_cache(apps, schema_editor):
    ParameterSet = apps.get_model('main', 'ParameterSet')
    ParameterSet.objects.all().update(json_for_session=None)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_alter_parametersetground_enable_clipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameterset',
            name='enable_chat',
            field=models.BooleanField(default=True, verbose_name='Enable Chat'),
        ),
        migrations.RunPython(clear_parameter_set_json_cache, noop_reverse),
    ]
