# Generated by Django 5.2.13 on 2026-05-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_parameterset_enable_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='esi_auth_access_token',
            field=models.CharField(default='', max_length=1000, verbose_name='ESI Auth Access Token'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='esi_auth_refresh_token',
            field=models.CharField(default='', max_length=1000, verbose_name='ESI Auth Refresh Token'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='esi_auth_token_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ESI Auth Token Expiration'),
        ),
    ]
