# Generated by Django 5.2.14 on 2026-05-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_parameters_esi_auth_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='email_ms_auth_access_token',
            field=models.CharField(default='', max_length=1000, verbose_name='Email MS Auth Access Token'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='email_ms_auth_refresh_token',
            field=models.CharField(default='', max_length=1000, verbose_name='Email MS Auth Refresh Token'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='email_ms_auth_token_expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email MS Auth Token Expiration'),
        ),
    ]
