# Generated by Django 5.2.12 on 2026-05-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0077_parameters_email_ms_auth_access_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='email_ms_auth_access_token',
            new_name='email_ms_access_token',
        ),
        migrations.RenameField(
            model_name='parameters',
            old_name='email_ms_auth_refresh_token',
            new_name='email_ms_refresh_token',
        ),
        migrations.RenameField(
            model_name='parameters',
            old_name='email_ms_auth_token_expiration',
            new_name='email_ms_token_expiration',
        ),
    ]
