# Generated by Django 5.2.16 on 2026-09-11 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0079_delete_parametersetbarrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametersetwall',
            name='parameter_set',
        ),
        migrations.DeleteModel(
            name='ParameterSetNotice',
        ),
        migrations.DeleteModel(
            name='ParameterSetWall',
        ),
    ]
